### PR TITLE
adding julia language

### PR DESCRIPTION
**Pull request by neomatrixcode**

### CODE REVIEW

**Comment by boyney123** [comment]
Hey @codeneomatrix

Thanks for the pull request.

I can see you are adding a new category, but no content to go inside?

**Comment by neomatrixcode** [comment]
hi, how do I add content?

**Comment by boyney123** [comment]
@codeneomatrix hopefully this can help? https://github.com/boyney123/graphql.explore-tech.org/blob/master/CONTRIBUTING.md

**Comment by neomatrixcode** [comment]
thank you

**Comment by boyney123** [comment]
Going to close the PR @codeneomatrix , feel free to make a PR with new categories/pages if you like. 

closing due to it just being a new category without any pages.

**Pull request closed without merging**
