### PR TITLE
GraphCMS tool addition

### PR DESCRIPTION
**Pull request by KenzoBenzo**

### CODE REVIEW

**Comment by KenzoBenzo** [comment]
Hey @boyney123! It appears as if the failed checks are for content on other tools/projects! Is there anything more you need of me to get this merged?

Cheers!

**Comment by KenzoBenzo** [comment]
Hey @boyney123 wanted to ping you on this again!

**Comment by boyney123** [comment]
Hey @KenzoBenzo 

Just had a look at looks like the image is broken?

image

You can see a preview here.

https://deploy-preview-3--graphql-explore-tech.netlify.com/Tools

Fancy looking into it?

**Comment by KenzoBenzo** [comment]
Hey, @boyney123 I will look into it tomorrow! Thanks for the heads-up!

**Comment by KenzoBenzo** [comment]
Hey @boyney123 this screenshot should work better!

**Pull request closed without merging**
